# Dependencies
markdown:         kramdown
highlighter:      pygments
plugins:
  - jekyll-paginate

  # Permalinks
permalink:        pretty

# Setup
title:            Death in Videogames
description:      'Examining the relationship between games and death'
url:              https://www.deathinvideogames.com
baseurl:          /

author:
  name:           'The Author'

paginate:         1
